LSS_TYPE = 'LSSTransform'
_KPT_META_KEYS = [
    'lidar_aug_matrix',
    'img_aug_matrix',
    'ego2global',
    'cam2global',
    'lidar_points',
    'cam2img',
    'ori_cam2img',
    'lidar2cam',
    'lidar2img',
    'cam2lidar',
    'ori_lidar2img',
    'box_type_3d',
    'sample_idx',
    'lidar_path',
    'img_path',
    'transformation_3d_flow',
    'pcd_rotation',
    'pcd_scale_factor',
    'pcd_trans',
    'num_pts_feats',
]
_META_KEYS = [
    'ego2global',
    'lidar_points',
    'lidar2img',
    'cam2img',
    'cam2lidar',
    'img_aug_matrix',
    'lidar_aug_matrix',
    'img_path',
    'lidar_path',
]
ann_file_train = 'pad_scenes_infos_train.pkl'
ann_file_val = 'pad_scenes_infos_val.pkl'
auto_scale_lr = dict(base_batch_size=32, enable=False)
backend_args = None
class_names = [
    'car',
    'bicycle',
    'pedestrian',
]
custom_hooks = []
custom_imports = dict(
    allow_failed_imports=False,
    imports=[
        'bevmatch',
    ])
data_prefix = dict(
    CAM_BACK='samples/CAM_BACK',
    CAM_FRONT='samples/CAM_FRONT',
    CAM_LEFT='samples/CAM_LEFT',
    CAM_RIGHT='samples/CAM_RIGHT',
    pts='samples/LIDAR_TOP',
    sweeps='sweeps/LIDAR_TOP')
data_root = 'data/kitti_odom/'
dataset_type = 'KittiOdometryKeypoints'
db_sampler = dict(
    classes=[
        'car',
        'truck',
        'construction_vehicle',
        'bus',
        'trailer',
        'barrier',
        'motorcycle',
        'bicycle',
        'pedestrian',
        'traffic_cone',
    ],
    data_root='data/nuscenes/',
    info_path='data/nuscenes/nuscenes_dbinfos_train.pkl',
    points_loader=dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=[
            0,
            1,
            2,
            3,
            4,
        ]),
    prepare=dict(
        filter_by_difficulty=[
            -1,
        ],
        filter_by_min_points=dict(
            barrier=5,
            bicycle=5,
            bus=5,
            car=5,
            construction_vehicle=5,
            motorcycle=5,
            pedestrian=5,
            traffic_cone=5,
            trailer=5,
            truck=5)),
    rate=1.0,
    sample_groups=dict(
        barrier=2,
        bicycle=6,
        bus=4,
        car=2,
        construction_vehicle=7,
        motorcycle=6,
        pedestrian=2,
        traffic_cone=2,
        trailer=6,
        truck=3))
default_hooks = dict(
    checkpoint=dict(interval=1, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(draw=False, interval=10, type='Det3DVisualizationHook'))
default_scope = 'mmdet3d'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
find_unused_parameters = True
input_modality = dict(use_camera=True, use_lidar=True)
load_from = None
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
lr = 5e-05
map_classes = [
    'drivable_urban',
    'drivable_offroad',
    'sidewalk',
    'high_grass',
    'low_grass',
    'bikeway',
    'stop_line',
    'lane_divider',
    'road_divider',
    'zebra_crossing',
    'other_markings',
    'parking_area',
]
metainfo = dict(classes=[
    'car',
    'bicycle',
    'pedestrian',
])
model = dict(
    bbox_head=None,
    data_preprocessor=dict(
        bgr_to_rgb=False,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        pad_size_divisor=32,
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='Det3DDataPreprocessorKeypoints',
        voxelize_cfg=dict(
            max_num_points=10,
            max_voxels=[
                120000,
                160000,
            ],
            point_cloud_range=[
                -54.0,
                -54.0,
                -5.0,
                54.0,
                54.0,
                3.0,
            ],
            voxel_size=[
                0.075,
                0.075,
                0.2,
            ],
            voxelize_reduce=True)),
    fusion_layer=dict(
        in_channels=[
            80,
            256,
        ], out_channels=256, type='ConvFuser'),
    img_backbone=dict(
        depth=50,
        norm_cfg=dict(requires_grad=True, type='BN'),
        norm_eval=False,
        num_stages=4,
        out_indices=(
            1,
            2,
            3,
        ),
        style='pytorch',
        type='mmdet.ResNet'),
    img_neck=dict(
        act_cfg=dict(inplace=True, type='ReLU'),
        in_channels=[
            512,
            1024,
            2048,
        ],
        norm_cfg=dict(requires_grad=True, type='BN'),
        num_outs=3,
        out_channels=256,
        start_level=0,
        type='GeneralizedLSSFPN',
        upsample_cfg=dict(align_corners=False, mode='bilinear')),
    keypoint_head=dict(
        binary_descriptor=False,
        covariance_max_rot_deg=20.0,
        covariance_max_trans_cells=20.0,
        covariance_weight=2.0,
        descriptor_loss_weight=1.0,
        detach_score_head=True,
        geometric_max_targets=40,
        geometric_min_score=0.1,
        info_nce_negative_mode='hard',
        kpt_artifact_mask=True,
        kpt_mask_border=8,
        kpt_mask_center_halfwidth=4,
        kpt_warmup_phase=2000,
        kpt_warmup_steps=2000,
        l_sparsity=5e-05,
        local_hard_neg=True,
        repulsion_distance=4.0,
        repulsion_weight=0.3,
        sparse_dense_blend=0.2,
        sparse_keypoint_descriptor=True,
        supervised=False,
        type='KeypointHead',
        use_geometric_targets=True),
    pts_backbone=dict(
        conv_cfg=dict(bias=False, type='Conv2d'),
        in_channels=256,
        layer_nums=[
            5,
            5,
        ],
        layer_strides=[
            1,
            2,
        ],
        norm_cfg=dict(eps=0.001, momentum=0.01, type='BN'),
        out_channels=[
            128,
            256,
        ],
        type='SECOND'),
    pts_middle_encoder=dict(
        block_type='basicblock',
        encoder_channels=(
            (
                16,
                16,
                32,
            ),
            (
                32,
                32,
                64,
            ),
            (
                64,
                64,
                128,
            ),
            (
                128,
                128,
            ),
        ),
        encoder_paddings=(
            (
                0,
                0,
                1,
            ),
            (
                0,
                0,
                1,
            ),
            (
                0,
                0,
                (
                    1,
                    1,
                    0,
                ),
            ),
            (
                0,
                0,
            ),
        ),
        in_channels=4,
        norm_cfg=dict(eps=0.001, momentum=0.01, type='BN1d'),
        order=(
            'conv',
            'norm',
            'act',
        ),
        sparse_shape=[
            1440,
            1440,
            41,
        ],
        type='BEVFusionSparseEncoder'),
    pts_neck=dict(
        in_channels=[
            128,
            256,
        ],
        norm_cfg=dict(eps=0.001, momentum=0.01, type='BN'),
        out_channels=[
            256,
            256,
        ],
        type='SECONDFPN',
        upsample_cfg=dict(bias=False, type='deconv'),
        upsample_strides=[
            1,
            2,
        ],
        use_conv_for_no_stride=True),
    pts_voxel_encoder=dict(num_features=4, type='HardSimpleVFE'),
    seg_head=None,
    type='BEVFusionKeypoints',
    use_camera=True,
    use_lidar=True,
    view_transform=dict(
        dbound=[
            1.0,
            60.0,
            0.5,
        ],
        downsample=2,
        feature_size=[
            32,
            88,
        ],
        image_size=[
            256,
            704,
        ],
        in_channels=256,
        out_channels=80,
        type='DepthLSSTransform',
        xbound=[
            -54.0,
            54.0,
            0.3,
        ],
        ybound=[
            -54.0,
            54.0,
            0.3,
        ],
        zbound=[
            -10.0,
            10.0,
            20.0,
        ]))
model_wrapper_cfg = dict(
    find_unused_parameters=True, type='MMDistributedDataParallel')
optim_wrapper = dict(
    clip_grad=dict(max_norm=35, norm_type=2),
    optimizer=dict(lr=3e-05, type='AdamW', weight_decay=0.01),
    type='OptimWrapper')
point_cloud_range = [
    -54.0,
    -54.0,
    -5.0,
    54.0,
    54.0,
    3.0,
]
resume = False
test_cfg = dict()
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='data/kitti_odom/kitti_odom_infos_val.pkl',
        pipeline=[
            dict(to_float32=True, type='LoadImageFromFile'),
            dict(type='WrapSingleImageAsMultiView'),
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=4,
                type='LoadPointsFromFile',
                use_dim=4),
            dict(
                bot_pct_lim=[
                    0.0,
                    0.0,
                ],
                final_dim=[
                    256,
                    704,
                ],
                is_train=False,
                rand_flip=False,
                resize_lim=[
                    0.7,
                    0.7,
                ],
                rot_lim=[
                    0.0,
                    0.0,
                ],
                type='ImageAug3D'),
            dict(
                rot_range=[
                    0.0,
                    0.0,
                ],
                scale_ratio_range=[
                    1.0,
                    1.0,
                ],
                translation_std=[
                    0.0,
                    0.0,
                    0.0,
                ],
                type='BEVFusionGlobalRotScaleTrans'),
            dict(
                point_cloud_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    54.0,
                    54.0,
                    3.0,
                ],
                type='PointsRangeFilter'),
            dict(
                keys=[
                    'points',
                    'img',
                ],
                meta_keys=[
                    'ego2global',
                    'lidar_points',
                    'lidar2img',
                    'cam2img',
                    'cam2lidar',
                    'img_aug_matrix',
                    'lidar_aug_matrix',
                    'img_path',
                    'lidar_path',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='KittiOdometryKeypoints'),
    drop_last=False,
    num_workers=1,
    persistent_workers=False,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file='data/kitti_odom/kitti_odom_infos_val.pkl',
    backend_args=None,
    data_root='data/kitti_odom/',
    metric='bbox',
    type='NuScenesMetricKeypoints')
test_pipeline = [
    dict(
        backend_args=None,
        color_type='color',
        to_float32=True,
        type='BEVLoadMultiViewImageFromFiles'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        dense_band_deg=(
            -7.0,
            5.0,
        ),
        dense_stride=5,
        type='KeepBeamsByElevation'),
    dict(
        bot_pct_lim=[
            0.0,
            0.0,
        ],
        final_dim=[
            256,
            704,
        ],
        is_train=False,
        rand_flip=False,
        resize_lim=[
            0.314,
            0.314,
        ],
        rot_lim=[
            0.0,
            0.0,
        ],
        type='ImageAug3D'),
    dict(
        rot_range=[
            0.0,
            0.0,
        ],
        scale_ratio_range=[
            1.0,
            1.0,
        ],
        translation_std=[
            0.0,
            0.0,
            0.0,
        ],
        type='BEVFusionGlobalRotScaleTrans'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            54.0,
            54.0,
            3.0,
        ],
        type='PointsRangeFilter'),
    dict(
        keys=[
            'points',
            'img',
        ],
        meta_keys=[
            'lidar_aug_matrix',
            'img_aug_matrix',
            'ego2global',
            'cam2global',
            'lidar_points',
            'cam2img',
            'ori_cam2img',
            'lidar2cam',
            'lidar2img',
            'cam2lidar',
            'ori_lidar2img',
            'box_type_3d',
            'sample_idx',
            'lidar_path',
            'img_path',
            'transformation_3d_flow',
            'pcd_rotation',
            'pcd_scale_factor',
            'pcd_trans',
        ],
        type='Pack3DDetInputs'),
]
test_pipeline_kitti = [
    dict(to_float32=True, type='LoadImageFromFile'),
    dict(type='WrapSingleImageAsMultiView'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=4,
        type='LoadPointsFromFile',
        use_dim=4),
    dict(
        bot_pct_lim=[
            0.0,
            0.0,
        ],
        final_dim=[
            256,
            704,
        ],
        is_train=False,
        rand_flip=False,
        resize_lim=[
            0.7,
            0.7,
        ],
        rot_lim=[
            0.0,
            0.0,
        ],
        type='ImageAug3D'),
    dict(
        rot_range=[
            0.0,
            0.0,
        ],
        scale_ratio_range=[
            1.0,
            1.0,
        ],
        translation_std=[
            0.0,
            0.0,
            0.0,
        ],
        type='BEVFusionGlobalRotScaleTrans'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            54.0,
            54.0,
            3.0,
        ],
        type='PointsRangeFilter'),
    dict(
        keys=[
            'points',
            'img',
        ],
        meta_keys=[
            'ego2global',
            'lidar_points',
            'lidar2img',
            'cam2img',
            'cam2lidar',
            'img_aug_matrix',
            'lidar_aug_matrix',
            'img_path',
            'lidar_path',
        ],
        type='Pack3DDetInputs'),
]
test_pipeline_tri = [
    dict(
        backend_args=None,
        color_type='color',
        to_float32=True,
        type='BEVLoadMultiViewImageFromFiles'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        dense_band_deg=(
            -7.0,
            5.0,
        ),
        dense_stride=5,
        type='KeepBeamsByElevation'),
    dict(
        type='LoadAnnotations3D',
        with_attr_label=False,
        with_bbox_3d=True,
        with_label_3d=True),
    dict(
        bot_pct_lim=[
            0.0,
            0.0,
        ],
        final_dim=[
            256,
            704,
        ],
        is_train=False,
        rand_flip=False,
        resize_lim=[
            0.314,
            0.314,
        ],
        rot_lim=[
            0.0,
            0.0,
        ],
        type='ImageAug3D'),
    dict(
        rot_range=[
            0.0,
            0.0,
        ],
        scale_ratio_range=[
            1.0,
            1.0,
        ],
        translation_std=[
            0.0,
            0.0,
            0.0,
        ],
        type='BEVFusionGlobalRotScaleTrans'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            54.0,
            54.0,
            3.0,
        ],
        type='PointsRangeFilter'),
    dict(
        classes=[
            'drivable_urban',
            'drivable_offroad',
            'sidewalk',
            'high_grass',
            'low_grass',
            'bikeway',
            'stop_line',
            'lane_divider',
            'road_divider',
            'zebra_crossing',
            'other_markings',
            'parking_area',
        ],
        dataset_root='data/kitti_odom/',
        load_terrain=False,
        type='LoadBEVMapsFromV3Image',
        xbound=[
            -54.0,
            54.0,
            0.6,
        ],
        ybound=[
            -54.0,
            54.0,
            0.6,
        ]),
    dict(
        keys=[
            'points',
            'img',
            'gt_bboxes_3d',
            'gt_labels_3d',
        ],
        meta_keys=[
            'lidar_aug_matrix',
            'img_aug_matrix',
            'ego2global',
            'cam2global',
            'lidar_points',
            'cam2img',
            'ori_cam2img',
            'lidar2cam',
            'lidar2img',
            'cam2lidar',
            'ori_lidar2img',
            'box_type_3d',
            'sample_idx',
            'lidar_path',
            'img_path',
            'transformation_3d_flow',
            'pcd_rotation',
            'pcd_scale_factor',
            'pcd_trans',
            'num_pts_feats',
            'gt_masks_bev',
        ],
        type='Pack3DDetInputs'),
]
train_cfg = dict(by_epoch=True, max_epochs=20, val_interval=1000)
train_dataloader = dict(
    batch_size=4,
    dataset=dict(
        ann_file='data/kitti_odom/kitti_odom_infos_train.pkl',
        pipeline=[
            dict(to_float32=True, type='LoadImageFromFile'),
            dict(type='WrapSingleImageAsMultiView'),
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=4,
                type='LoadPointsFromFile',
                use_dim=4),
            dict(
                bot_pct_lim=[
                    0.0,
                    0.0,
                ],
                final_dim=[
                    256,
                    704,
                ],
                is_train=False,
                rand_flip=False,
                resize_lim=[
                    0.7,
                    0.7,
                ],
                rot_lim=[
                    0.0,
                    0.0,
                ],
                type='ImageAug3D'),
            dict(
                rot_range=[
                    0.0,
                    0.0,
                ],
                scale_ratio_range=[
                    1.0,
                    1.0,
                ],
                translation_std=[
                    0.0,
                    0.0,
                    0.0,
                ],
                type='BEVFusionGlobalRotScaleTrans'),
            dict(
                point_cloud_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    54.0,
                    54.0,
                    3.0,
                ],
                type='PointsRangeFilter'),
            dict(
                keys=[
                    'points',
                    'img',
                ],
                meta_keys=[
                    'ego2global',
                    'lidar_points',
                    'lidar2img',
                    'cam2img',
                    'cam2lidar',
                    'img_aug_matrix',
                    'lidar_aug_matrix',
                    'img_path',
                    'lidar_path',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=False,
        type='KittiOdometryKeypoints'),
    num_workers=6,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(
        backend_args=None,
        color_type='color',
        to_float32=True,
        type='BEVLoadMultiViewImageFromFiles'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        dense_band_deg=(
            -7.0,
            5.0,
        ),
        dense_stride=5,
        type='KeepBeamsByElevation'),
    dict(
        bot_pct_lim=[
            0.0,
            0.0,
        ],
        final_dim=[
            256,
            704,
        ],
        is_train=True,
        rand_flip=True,
        resize_lim=[
            0.28,
            0.34,
        ],
        rot_lim=[
            0.0,
            0.0,
        ],
        type='ImageAug3D'),
    dict(
        rot_range=[
            0.0,
            0.0,
        ],
        scale_ratio_range=[
            0.9,
            1.1,
        ],
        translation_std=[
            0.5,
            0.5,
            0.5,
        ],
        type='BEVFusionGlobalRotScaleTrans'),
    dict(type='BEVFusionRandomFlip3D'),
    dict(
        box_size_m=(
            3.0,
            12.0,
        ),
        extent_m=30.0,
        prob=0.2,
        type='RandomLiDARBoxDropout'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            54.0,
            54.0,
            3.0,
        ],
        type='PointsRangeFilter'),
    dict(
        keys=[
            'points',
            'img',
        ],
        meta_keys=[
            'lidar_aug_matrix',
            'img_aug_matrix',
            'ego2global',
            'cam2global',
            'lidar_points',
            'cam2img',
            'ori_cam2img',
            'lidar2cam',
            'lidar2img',
            'cam2lidar',
            'ori_lidar2img',
            'box_type_3d',
            'sample_idx',
            'lidar_path',
            'img_path',
            'transformation_3d_flow',
            'pcd_rotation',
            'pcd_scale_factor',
            'pcd_trans',
        ],
        type='Pack3DDetInputs'),
]
train_pipeline_kitti = [
    dict(to_float32=True, type='LoadImageFromFile'),
    dict(type='WrapSingleImageAsMultiView'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=4,
        type='LoadPointsFromFile',
        use_dim=4),
    dict(
        bot_pct_lim=[
            0.0,
            0.0,
        ],
        final_dim=[
            256,
            704,
        ],
        is_train=False,
        rand_flip=False,
        resize_lim=[
            0.7,
            0.7,
        ],
        rot_lim=[
            0.0,
            0.0,
        ],
        type='ImageAug3D'),
    dict(
        rot_range=[
            0.0,
            0.0,
        ],
        scale_ratio_range=[
            1.0,
            1.0,
        ],
        translation_std=[
            0.0,
            0.0,
            0.0,
        ],
        type='BEVFusionGlobalRotScaleTrans'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            54.0,
            54.0,
            3.0,
        ],
        type='PointsRangeFilter'),
    dict(
        keys=[
            'points',
            'img',
        ],
        meta_keys=[
            'ego2global',
            'lidar_points',
            'lidar2img',
            'cam2img',
            'cam2lidar',
            'img_aug_matrix',
            'lidar_aug_matrix',
            'img_path',
            'lidar_path',
        ],
        type='Pack3DDetInputs'),
]
train_pipeline_noaug = [
    dict(
        backend_args=None,
        color_type='color',
        to_float32=True,
        type='BEVLoadMultiViewImageFromFiles'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        dense_band_deg=(
            -7.0,
            5.0,
        ),
        dense_stride=5,
        type='KeepBeamsByElevation'),
    dict(
        bot_pct_lim=[
            0.0,
            0.0,
        ],
        final_dim=[
            256,
            704,
        ],
        is_train=False,
        rand_flip=False,
        resize_lim=[
            0.314,
            0.314,
        ],
        rot_lim=[
            0.0,
            0.0,
        ],
        type='ImageAug3D'),
    dict(
        rot_range=[
            0.0,
            0.0,
        ],
        scale_ratio_range=[
            1.0,
            1.0,
        ],
        translation_std=[
            0.0,
            0.0,
            0.0,
        ],
        type='BEVFusionGlobalRotScaleTrans'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            54.0,
            54.0,
            3.0,
        ],
        type='PointsRangeFilter'),
    dict(
        keys=[
            'points',
            'img',
        ],
        meta_keys=[
            'lidar_aug_matrix',
            'img_aug_matrix',
            'ego2global',
            'cam2global',
            'lidar_points',
            'cam2img',
            'ori_cam2img',
            'lidar2cam',
            'lidar2img',
            'cam2lidar',
            'ori_lidar2img',
            'box_type_3d',
            'sample_idx',
            'lidar_path',
            'img_path',
            'transformation_3d_flow',
            'pcd_rotation',
            'pcd_scale_factor',
            'pcd_trans',
        ],
        type='Pack3DDetInputs'),
]
train_pipeline_tri = [
    dict(
        backend_args=None,
        color_type='color',
        to_float32=True,
        type='BEVLoadMultiViewImageFromFiles'),
    dict(
        backend_args=None,
        coord_type='LIDAR',
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        dense_band_deg=(
            -7.0,
            5.0,
        ),
        dense_stride=5,
        type='KeepBeamsByElevation'),
    dict(
        type='LoadAnnotations3D',
        with_attr_label=False,
        with_bbox_3d=True,
        with_label_3d=True),
    dict(
        bot_pct_lim=[
            0.0,
            0.0,
        ],
        final_dim=[
            256,
            704,
        ],
        is_train=False,
        rand_flip=False,
        resize_lim=[
            0.314,
            0.314,
        ],
        rot_lim=[
            0.0,
            0.0,
        ],
        type='ImageAug3D'),
    dict(
        rot_range=[
            0.0,
            0.0,
        ],
        scale_ratio_range=[
            1.0,
            1.0,
        ],
        translation_std=[
            0.0,
            0.0,
            0.0,
        ],
        type='BEVFusionGlobalRotScaleTrans'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            54.0,
            54.0,
            3.0,
        ],
        type='PointsRangeFilter'),
    dict(
        point_cloud_range=[
            -54.0,
            -54.0,
            -5.0,
            54.0,
            54.0,
            3.0,
        ],
        type='ObjectRangeFilter'),
    dict(classes=[
        'car',
        'bicycle',
        'pedestrian',
    ], type='ObjectNameFilter'),
    dict(
        classes=[
            'drivable_urban',
            'drivable_offroad',
            'sidewalk',
            'high_grass',
            'low_grass',
            'bikeway',
            'stop_line',
            'lane_divider',
            'road_divider',
            'zebra_crossing',
            'other_markings',
            'parking_area',
        ],
        dataset_root='data/kitti_odom/',
        load_terrain=False,
        type='LoadBEVMapsFromV3Image',
        xbound=[
            -54.0,
            54.0,
            0.6,
        ],
        ybound=[
            -54.0,
            54.0,
            0.6,
        ]),
    dict(
        keys=[
            'points',
            'img',
            'gt_bboxes_3d',
            'gt_labels_3d',
        ],
        meta_keys=[
            'lidar_aug_matrix',
            'img_aug_matrix',
            'ego2global',
            'cam2global',
            'lidar_points',
            'cam2img',
            'ori_cam2img',
            'lidar2cam',
            'lidar2img',
            'cam2lidar',
            'ori_lidar2img',
            'box_type_3d',
            'sample_idx',
            'lidar_path',
            'img_path',
            'transformation_3d_flow',
            'pcd_rotation',
            'pcd_scale_factor',
            'pcd_trans',
            'num_pts_feats',
            'gt_masks_bev',
        ],
        type='Pack3DDetInputs'),
]
val_cfg = dict()
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='data/kitti_odom/kitti_odom_infos_val.pkl',
        pipeline=[
            dict(to_float32=True, type='LoadImageFromFile'),
            dict(type='WrapSingleImageAsMultiView'),
            dict(
                backend_args=None,
                coord_type='LIDAR',
                load_dim=4,
                type='LoadPointsFromFile',
                use_dim=4),
            dict(
                bot_pct_lim=[
                    0.0,
                    0.0,
                ],
                final_dim=[
                    256,
                    704,
                ],
                is_train=False,
                rand_flip=False,
                resize_lim=[
                    0.7,
                    0.7,
                ],
                rot_lim=[
                    0.0,
                    0.0,
                ],
                type='ImageAug3D'),
            dict(
                rot_range=[
                    0.0,
                    0.0,
                ],
                scale_ratio_range=[
                    1.0,
                    1.0,
                ],
                translation_std=[
                    0.0,
                    0.0,
                    0.0,
                ],
                type='BEVFusionGlobalRotScaleTrans'),
            dict(
                point_cloud_range=[
                    -54.0,
                    -54.0,
                    -5.0,
                    54.0,
                    54.0,
                    3.0,
                ],
                type='PointsRangeFilter'),
            dict(
                keys=[
                    'points',
                    'img',
                ],
                meta_keys=[
                    'ego2global',
                    'lidar_points',
                    'lidar2img',
                    'cam2img',
                    'cam2lidar',
                    'img_aug_matrix',
                    'lidar_aug_matrix',
                    'img_path',
                    'lidar_path',
                ],
                type='Pack3DDetInputs'),
        ],
        test_mode=True,
        type='KittiOdometryKeypoints'),
    drop_last=False,
    num_workers=1,
    persistent_workers=False,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file='data/kitti_odom/kitti_odom_infos_val.pkl',
    backend_args=None,
    data_root='data/kitti_odom/',
    metric='bbox',
    type='NuScenesMetricKeypoints')
vis_backends = [
    dict(type='LocalVisBackend'),
    dict(type='TensorboardVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='Det3DLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
        dict(type='TensorboardVisBackend'),
    ])
voxel_size = [
    0.075,
    0.075,
    0.2,
]
